--liquibase formatted sql
--changeset i.german:v1_init

create schema if not exists banking;

create table if not exists banking.user
(
    id            bigint generated by default as identity primary key,
    name          varchar(500) not null,
    date_of_birth date,
    password      varchar(500) check ( length(password) >= 8 )
);

create table if not exists banking.account
(
    id             bigint generated by default as identity primary key,
    user_id        bigint  not null unique,
    balance        decimal not null default 0,
    bonus_credited boolean not null default false,
    foreign key (user_id) references banking.user (id) on delete cascade
);

create table if not exists banking.email_data
(
    id      bigint generated by default as identity primary key,
    user_id bigint       not null,
    email   varchar(200) not null unique,
    foreign key (user_id) references banking.user (id) on delete cascade
);

create table banking.phone_data
(
    id      bigint generated by default as identity primary key,
    user_id bigint      not null,
    phone   varchar(13) not null unique,
    foreign key (user_id) references banking.user (id) on delete cascade
);


